### PR TITLE
Branch/notification attribute

### PR DESCRIPTION
**Pull request by aquamoth**
## Only notify on actual _change_ of an auto-property

This code **does not** change existing default behaviour. The new functionality is achieved by adding a constructor argument (`NotifyMode`: `OnSet` or `OnChange`) to the `Notify` attribute and extending the `Notifier` attribute's `NotificationMode` with `ImplicitOnChange`.

In your original version I mistakenly thought the setter didn't notify target when set value was same as existing. This is a really important feature for me since we constantly pull state from underlying (c++) subsystems and don't want to check for change before setting our MVVM-properties.

To get this working I had to refactor some of your existing code. I added a couple of detailed unit tests to make sure I didn't inadvertently change existing functionality. I didn't touch the existing unit test.

I really hope you want to include this in the official repo because I don't want to maintain a fork. Unfortunately you've already made some heavy refactoring in `MIST-2.0` before I was ready to push. If you like what I've done but _don't_ want to forward-implement it into `MIST-2.0` yourself I can look at redo my work on top of the new branch when you've stabilized.

Let me know what you think

### CODE REVIEW

**Comment by mathtone** [comment]
Hi aquamoth, I'm doing some refactoring of the core code right now.  I do intend to in include this feature in the main branch.  My plan is to turn the NotificationMode enum into a set of flags and add some values so that the notificationmode can be something like: (NotificationMode.Implicit | NotificationMode.OnChangeOnly) if that makes sense.  I'll try to merge everything and push a new package out tonight or tomorrow.

**Comment by aquamoth** [comment]
I considered flags too at first, though it was too large change to do in someone elses code.

Then I realized that Implicit/Explicit NotificationMode describes the class while OnChange/OnSet really describe individual properties. Thus I think my suggested split makes more sense.

Anyway, great news you appreciate the functionality. :)

mik3c notifications@github.com skrev: (5 juni 2016 22:31:05 CEST)

> Hi aquamoth, I'm doing some refactoring of the core code right now.  I
> do intend to in include this feature in the main branch.  My plan is to
> turn the NotificationMode enum into a set of flags and add some values
> so that the notificationmode can be something like:
> (NotificationMode.Implicit | NotificationMode.OnChangeOnly) if that
> makes sense.  I'll try to merge everything and push a new package out
> tonight or tomorrow.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mathtone/MIST/pull/5#issuecomment-223835801

## 

Med vänliga hälsningar,

Mattias Åslund
Trustfall AB
mattias@trustfall.se
0734-309007

**Comment by mathtone** [comment]
Yeah I think you're probably right about that, I wanted to be able to specify the default behavior for classes using implicit notification but it looks like your solution achieves that.    I think having enums called NotificationMode and NotifyMode might be a little confusing.  Maybe NotificationMode and NotificationStyle or NotifyStyle?

**Comment by mathtone** [comment]
I'll knit all this back together and put up another build.  Thanks for your input, I think with a little bit of polish this could be a great utility.

**Comment by aquamoth** [comment]
I agree they're too similar. I wanted the Mode to reflect which attribute it affected.

I'm sure you'll come to a good decision on naming. :)

mik3c notifications@github.com skrev: (6 juni 2016 00:22:15 CEST)

> Yeah I think you're probably right about that, I wanted to be able to
> specify the default behavior for classes using implicit notification
> but it looks like your solution achieves that.    I think having enums
> called NotificationMode and NotifyMode might be a little confusing. 
> Maybe NotificationMode and NotificationStyle or NotifyStyle?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mathtone/MIST/pull/5#issuecomment-223841451

## 

Med vänliga hälsningar,

Mattias Åslund
Trustfall AB
mattias@trustfall.se
0734-309007

**Comment by aquamoth** [comment]
Are you pushing a nuget-package for this release too? Would be useful...

**Comment by mathtone** [comment]
Yes it's almost ready, I'll put the nuget package together tonight and roll it out.

**Comment by mathtone** [comment]
I just pushed a new package out, I changed a few things but it looks like the functionality you needed is in there.  I made a few changes to your unit tests as well but they all pass.  Have  alook and let me know what you think.

**Comment by aquamoth** [comment]
I've read through the code changes you've made since my PR. This is what I think of it:
- This will be a really useful package that makes our own code a lot more readable.
- It's good you implemented the unit test notifiers as spies instead of complicating things with events.
- That you are moving towards more short and specific unit tests instead of large monoliths is good.
- It's redundant to prefix the unit test with "Test". They all are.
- Clear naming of test methods helps describe what they do - especially when they fail. 
  - What is "TestNotifierNotifierNotifier" really supposed to tell me?
  - In the same line; If "TestNotifier5" was renamed to "NotifyOnChangeSpy" it would better explain to me what it's intended to do.
- I like the interface IChangeTracker. It makes the spies more consistent.
- Now you and I have written so many notifiers I bet some do the same thing, but with different naming standards. Ditch one standard and normalize the code for simpler maintainence. (Of course I think my way is better... ;)
- I definitely like how you've clean up the code by introducing a bunch of specific Processors instead of the huge monolith NotificationWeaver used to be!

**Comment by mathtone** [comment]
Agreed on all points.  I'm going to adopt your standard for naming the
tests, normalize those and clean them up. Right now though there seems to
be some other issue with OnChange notifications, so I'm going to try and
sort that out.  It was getting late and I was anxious to push a package out
so I must have missed something.

**Pull request merged**
